services:
  - docker
before_install:
- git submodule update --init --recursive
- docker pull klakegg/hugo:0.64.0
script:
- | 
  docker run --rm -it \
  -v $(pwd):/src \
  -v $(pwd)/output:/target \
  klakegg/hugo:0.64.0
deploy:
  provider: pages
  local_dir: output
  github_token: "$GITHUB_TOKEN"
  verbose: true
  skip_cleanup: true
  repo: Sam-Martin/sammartin.github.io
  fqdn: sammart.in
  target_branch: master
