before_install:
- git submodule update --init --recursive
- |
  echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"
  wget https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_0.61.0_Linux-64bit.deb -O /tmp/hugo.deb &> /dev/null
  sudo dpkg -i /tmp/hugo.deb &> /dev/null
  hugo version
  echo -e "\ntravis_fold:end:$1\r"
script:
- ls -lha assets/css
- hugo -D --debug --verbose
- find . -name \*css\* | xargs -I '{}' shasum {}
deploy:
  provider: pages
  local_dir: publice
  github_token: "$GITHUB_TOKEN"
  verbose: true
  repo: Sam-Martin/sammartin.github.io
  fqdn: sammart.in