baseURL = "https://sammart.in/"
languageCode = "en-gb"
title = "Sam Martin"
theme = "m10c"
googleAnalytics = "UA-66377745-1"
pygmentsUseClasses=true

disqusShortname="sammartin"

[params]
    description = "Adventures in IT"
    author = "Sam Martin"
[params.style]
  darkestColor = "#264d8f"
  darkColor = "#ffff"
  lightColor = "#000"
  lightestColor = "#000"
  primaryColor = "#000"
