baseURL = "http://sammart.in/"
languageCode = "en-gb"
title = "Sam Martin"
theme = "m10c"

[params]
    description = "Adventures in IT"
    author = "Sam Martin"
[params.style]
  darkestColor = "#264d8f"
  darkColor = "#ffff"
  lightColor = "#000"
  lightestColor = "#000"
  primaryColor = "#000"